# https://bitbucket.org/nrbusinesssystems/bitbucket-pipeline-image/src/master/
image: networkrail/networkrail:7.4

pipelines:
    default:
        - step:
              caches:
                  - composer
              script:
                  - composer install --no-progress --no-suggest --prefer-dist
                  - vendor/bin/phpunit
